### ISSUE TITLE
zh-TW should *never* fall-back to zh-CN

### ISSUE THREAD

**Issue by stephendonner** [mozilla/marketing-project-template#5]
This came up during our Firefox Flicks post-mortem: zh-TW should _never_ fall-back to zh-CN.

It should always:
- either stay at zh-TW
- fall-back to en-US

**Comment by rbillings** [comment]
Assigning to myself

**Comment by rbillings** [comment]
Closing issue for now.

**Comment by davehunt** [comment]
Judging by the last comment, I think this issue should be closed.
